version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    target-branch: "dependabot-updates"   # not develop
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # 👇  Add
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
