updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    # only security updates
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-type: "all"
