version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install boto3
      
  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      - echo "Checking AWS credentials..."
      - aws sts get-caller-identity
      
  build:
    commands:
      - echo "Build phase started on `date`"
      - echo "Deploying enhanced Lambda function..."
      - chmod +x deploy-lambda-fix.sh
      - ./deploy-lambda-fix.sh
      
  post_build:
    commands:
      - echo "Post-build phase started on `date`"
      - echo "Running system test to verify fixes..."
      - ./test-complete-system.sh
      
artifacts:
  files:
    - '**/*'
