export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}", "./src/**/*.css"],
  safelist: [
    "peer",
    "peer-focus",
    "peer-placeholder-shown",
    "peer-[:not(:placeholder-shown)]",
    "peer-[&:not(:placeholder-shown)]",
    "text-xs",
    "top-2",
    "text-green-600",
    "rounded-xl",
    "bg-white",
    "text-gray-900",
    "h-12",
  ],
  theme: {
    extend: {
      colors: {
        // Legacy tokens (keep for backwards compatibility)
        primary: "var(--color-primary)",
        secondary: "var(--color-secondary)",
        accent: "var(--color-accent)",
        neutral: "var(--color-neutral)",
        "bg-default": "var(--color-bg-default)",
        "text-default": "var(--color-text-default)",
        
        // New design tokens for UX refresh
        bg: "var(--color-bg)",
        surface: "var(--color-surface)",
        border: "var(--color-border)",
        "secondary-new": "var(--color-secondary)",
        "accent-new": "var(--color-accent)",
        "accent-contrast": "var(--color-accent-contrast)",
        text: "var(--color-text)",
        "text-muted": "var(--color-text-muted)",
        success: "var(--color-success)",
        warning: "var(--color-warning)",
        danger: "var(--color-danger)",
      },
      spacing: {
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        card: "var(--space-card)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "28px",
      },
      transitionDuration: {
        fast: "var(--transition-fast)",
        normal: "var(--transition-normal)",
        slow: "var(--transition-slow)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/typography")],
};
