AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless API for document generation and approval

Parameters:
  EmailFrom:
    Type: String
    Description: Email address used as the source for notifications
  Bucket:
    Type: String
    Description: S3 bucket name for generated documents

Resources:
  ApplicationApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  InvokePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: InvokeAll
      Roles: []
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: lambda:InvokeFunction
            Resource: arn:aws:lambda:us-east-2:703671891952:function:*

  GetTimeline:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/
      Handler: handler.lambda_handler
      Runtime: python3.12
      Events:
        Api:
          Type: Api
          Properties:
            Path: /timeline/{id}
            Method: get
            RestApiId: !Ref ApplicationApi
      Policies:
        - InvokePolicy

  GetDownloadActa:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/
      Handler: handler.lambda_handler
      Runtime: python3.12
      Events:
        Api:
          Type: Api
          Properties:
            Path: /download-acta/{id}
            Method: get
            RestApiId: !Ref ApplicationApi
      Policies:
        - InvokePolicy

  GetProjectSummary:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/
      Handler: handler.lambda_handler
      Runtime: python3.12
      Events:
        Api:
          Type: Api
          Properties:
            Path: /project-summary/{id}
            Method: get
            RestApiId: !Ref ApplicationApi
      Policies:
        - InvokePolicy

  SendApprovalEmail:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/
      Handler: handler.lambda_handler
      Runtime: python3.12
      Events:
        Api:
          Type: Api
          Properties:
            Path: /send-approval-email
            Method: post
            RestApiId: !Ref ApplicationApi
      Policies:
        - InvokePolicy

  ProjectPlaceDataExtractor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/
      Handler: handler.lambda_handler
      Runtime: python3.12
      Events:
        Api:
          Type: Api
          Properties:
            Path: /extract-project-place/{id}
            Method: post
            RestApiId: !Ref ApplicationApi
      Policies:
        - InvokePolicy

  TimelineParamStore:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /acta-ui/api/getTimeline
      Type: String
      Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/timeline'

  DownloadParamStore:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /acta-ui/api/getDownloadActa
      Type: String
      Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/download-acta'

  SummaryParamStore:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /acta-ui/api/getProjectSummary
      Type: String
      Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/project-summary'

  SendEmailParamStore:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /acta-ui/api/sendApprovalEmail
      Type: String
      Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/send-approval-email'

  ExtractParamStore:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /acta-ui/api/ProjectPlaceDataExtractor
      Type: String
      Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/extract-project-place'

Outputs:
  ApiUrl:
    Description: API endpoint URL
    Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'

  TimelineParam:
    Description: Timeline URL
    Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/timeline'
    Export:
      Name: /acta-ui/api/getTimeline

  DownloadParam:
    Description: Download URL
    Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/download-acta'
    Export:
      Name: /acta-ui/api/getDownloadActa

  SummaryParam:
    Description: Summary URL
    Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/project-summary'
    Export:
      Name: /acta-ui/api/getProjectSummary

  SendEmailParam:
    Description: Send approval email URL
    Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/send-approval-email'
    Export:
      Name: /acta-ui/api/sendApprovalEmail

  ExtractParam:
    Description: Extract ProjectPlace URL
    Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/extract-project-place'
    Export:
      Name: /acta-ui/api/ProjectPlaceDataExtractor
