AWSTemplateFormatVersion: '2010-09-09'
Description: CONFLICT-FREE API Gateway wiring (PM endpoints → projectMetadataEnricher)

###############################################################################
# Parameters
###############################################################################
Parameters:
  ExistingApiId:
    Type: String
    Default: q2b9avfwv5
  ExistingApiRootResourceId:
    Type: String
    Default: kw8f8zihjg
  ProjectMetadataEnricherArn:
    Type: String
    Default: arn:aws:lambda:us-east-2:703671891952:function:projectMetadataEnricher
  ProjectMetadataEnricherFunctionName:
    Type: String
    Default: projectMetadataEnricher
  DeploymentTimestamp:
    Type: String
    Default: "20250629-000000"

###############################################################################
# Helper: reusable MOCK OPTIONS method (CORS / “ping”)
###############################################################################
Mappings:
  MockOptionsTemplate:
    Properties:
      AuthorizationType: NONE
      HttpMethod: OPTIONS
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'GET,HEAD,OPTIONS,ANY'"
              method.response.header.Access-Control-Allow-Headers: "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Headers: true

###############################################################################
# API Gateway resources
###############################################################################
Resources:

  # ─── PM-MANAGER ─────────────────────────────────────────────
  PMManagerResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ExistingApiId
      ParentId:  !Ref ExistingApiRootResourceId
      PathPart:  pm-manager

  PMManagerAllProjectsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ExistingApiId
      ParentId:  !Ref PMManagerResource
      PathPart:  all-projects

  PMManagerByEmailResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ExistingApiId
      ParentId:  !Ref PMManagerResource
      PathPart:  '{pmEmail}'

  # ─── DOCUMENT-VALIDATOR ────────────────────────────────────
  DocumentValidatorResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ExistingApiId
      ParentId:  !Ref ExistingApiRootResourceId
      PathPart:  document-validator

  DocumentValidatorIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ExistingApiId
      ParentId:  !Ref DocumentValidatorResource
      PathPart:  '{projectId}'

  # ─── PROJECTS-MANAGER ──────────────────────────────────────
  ProjectsManagerResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ExistingApiId
      ParentId:  !Ref ExistingApiRootResourceId
      PathPart:  projects-manager

  # ─── NEW: projectMetadataEnricher PATH ─────────────────────
  ProjectMetadataEnricherResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ExistingApiId
      ParentId:  !Ref ExistingApiRootResourceId
      PathPart:  projectMetadataEnricher

  # ─── NEW: health PATH ──────────────────────────────────────
  HealthResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ExistingApiId
      ParentId:  !Ref ExistingApiRootResourceId
      PathPart:  health

###############################################################################
# Lambda-proxy methods
###############################################################################
  # PM-Manager
  PMManagerAllProjectsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:  !Ref ExistingApiId
      ResourceId: !Ref PMManagerAllProjectsResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProjectMetadataEnricherArn}/invocations

  PMManagerByEmailMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:  !Ref ExistingApiId
      ResourceId: !Ref PMManagerByEmailResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProjectMetadataEnricherArn}/invocations

  # Projects-Manager
  ProjectsManagerMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:  !Ref ExistingApiId
      ResourceId: !Ref ProjectsManagerResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProjectMetadataEnricherArn}/invocations

  # Document-Validator
  DocumentValidatorGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:  !Ref ExistingApiId
      ResourceId: !Ref DocumentValidatorIdResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProjectMetadataEnricherArn}/invocations

  DocumentValidatorHeadMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:  !Ref ExistingApiId
      ResourceId: !Ref DocumentValidatorIdResource
      HttpMethod: HEAD
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProjectMetadataEnricherArn}/invocations

  # NEW – ANY /projectMetadataEnricher
  ProjectMetadataEnricherMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:  !Ref ExistingApiId
      ResourceId: !Ref ProjectMetadataEnricherResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProjectMetadataEnricherArn}/invocations

  # NEW – GET /health
  HealthGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:  !Ref ExistingApiId
      ResourceId: !Ref HealthResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProjectMetadataEnricherArn}/invocations

###############################################################################
# MOCK OPTIONS for every resource (CORS & avoids “no integration”)
###############################################################################
  PMManagerOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:  !Ref ExistingApiId
      ResourceId: !Ref PMManagerResource
      Fn::Merge:
        - !FindInMap [MockOptionsTemplate, Properties]

  PMManagerAllProjectsOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:  !Ref ExistingApiId
      ResourceId: !Ref PMManagerAllProjectsResource
      Fn::Merge:
        - !FindInMap [MockOptionsTemplate, Properties]

  PMManagerByEmailOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:  !Ref ExistingApiId
      ResourceId: !Ref PMManagerByEmailResource
      Fn::Merge:
        - !FindInMap [MockOptionsTemplate, Properties]

  DocumentValidatorOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:  !Ref ExistingApiId
      ResourceId: !Ref DocumentValidatorResource
      Fn::Merge:
        - !FindInMap [MockOptionsTemplate, Properties]

  DocumentValidatorIdOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:  !Ref ExistingApiId
      ResourceId: !Ref DocumentValidatorIdResource
      Fn::Merge:
        - !FindInMap [MockOptionsTemplate, Properties]

  ProjectsManagerOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:  !Ref ExistingApiId
      ResourceId: !Ref ProjectsManagerResource
      Fn::Merge:
        - !FindInMap [MockOptionsTemplate, Properties]

  ProjectMetadataEnricherOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:  !Ref ExistingApiId
      ResourceId: !Ref ProjectMetadataEnricherResource
      Fn::Merge:
        - !FindInMap [MockOptionsTemplate, Properties]

  HealthOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:  !Ref ExistingApiId
      ResourceId: !Ref HealthResource
      Fn::Merge:
        - !FindInMap [MockOptionsTemplate, Properties]

###############################################################################
# Lambda permissions
###############################################################################
  # (unchanged original five) … plus:
  ProjectMetadataEnricherPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ProjectMetadataEnricherFunctionName
      Action:  lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ExistingApiId}/*/*/projectMetadataEnricher

  HealthPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ProjectMetadataEnricherFunctionName
      Action:  lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ExistingApiId}/*/GET/health

###############################################################################
# Deployment & Stage
###############################################################################
  ConflictFreeApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      # 8 Lambda-proxy methods
      - PMManagerAllProjectsMethod
      - PMManagerByEmailMethod
      - ProjectsManagerMethod
      - DocumentValidatorGetMethod
      - DocumentValidatorHeadMethod
      - ProjectMetadataEnricherMethod
      - HealthGetMethod
      - ProjectMetadataEnricherOptionsMethod   # options count as methods
      # 8 OPTIONS mock methods
      - PMManagerOptionsMethod
      - PMManagerAllProjectsOptionsMethod
      - PMManagerByEmailOptionsMethod
      - DocumentValidatorOptionsMethod
      - DocumentValidatorIdOptionsMethod
      - ProjectsManagerOptionsMethod
      - HealthOptionsMethod
      # 4 resources to guarantee creation order
      - PMManagerResource
      - DocumentValidatorResource
      - ProjectsManagerResource
      - ProjectMetadataEnricherResource
    Properties:
      RestApiId: !Ref ExistingApiId
      Description: !Sub "Conflict-free deployment ${DeploymentTimestamp}"

  ConflictFreeProdStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref ConflictFreeApiGatewayDeployment
      RestApiId:    !Ref ExistingApiId
      StageName:    prod
      Description:  !Sub "Prod stage ${DeploymentTimestamp}"

###############################################################################
# Outputs
###############################################################################
Outputs:
  APIGatewayId:
    Value: !Ref ExistingApiId
  DeploymentId:
    Value: !Ref ConflictFreeApiGatewayDeployment
  StageId:
    Value: !Ref ConflictFreeProdStage
  HealthEndpoint:
    Value: !Sub "https://${ExistingApiId}.execute-api.${AWS::Region}.amazonaws.com/prod/health"
  MetadataEnricherEndpoint:
    Value: !Sub "https://${ExistingApiId}.execute-api.${AWS::Region}.amazonaws.com/prod/projectMetadataEnricher"
