AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless API for document generation and approval

Parameters:
  EmailFrom:
    Type: String
    Description: Email address used as the source for notifications
  Bucket:
    Type: String
    Description: S3 bucket name for generated documents

Resources:
  ### ───────────────────── API  ─────────────────────
  ApplicationApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  ### ───────────────────── Functions  ───────────────
  GetTimeline:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/
      Handler: handler.lambda_handler
      Runtime: python3.12
      Events:
        Api:
          Type: Api
          Properties:
            Path: /timeline/{id}
            Method: GET
            RestApiId: !Ref ApplicationApi

  GetDownloadActa:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/
      Handler: handler.lambda_handler
      Runtime: python3.12
      Events:
        Api:
          Type: Api
          Properties:
            Path: /download-acta/{id}
            Method: GET
            RestApiId: !Ref ApplicationApi

  GetProjectSummary:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/
      Handler: handler.lambda_handler
      Runtime: python3.12
      Events:
        Api:
          Type: Api
          Properties:
            Path: /project-summary/{id}
            Method: GET
            RestApiId: !Ref ApplicationApi

  SendApprovalEmail:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/
      Handler: handler.lambda_handler
      Runtime: python3.12
      Events:
        Api:
          Type: Api
          Properties:
            Path: /send-approval-email
            Method: POST
            RestApiId: !Ref ApplicationApi

  ProjectPlaceDataExtractor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/
      Handler: handler.lambda_handler
      Runtime: python3.12
      Events:
        Api:
          Type: Api
          Properties:
            Path: /extract-project-place/{id}
            Method: POST
            RestApiId: !Ref ApplicationApi

            
  TimelineParamStore:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /acta-ui/api/getTimeline
      Type: String
      Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/timeline'

  DownloadParamStore:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /acta-ui/api/getDownloadActa
      Type: String
      Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/download-acta'

  SummaryParamStore:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /acta-ui/api/getProjectSummary
      Type: String
      Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/project-summary'

  SendEmailParamStore:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /acta-ui/api/sendApprovalEmail
      Type: String
      Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/send-approval-email'

  ExtractParamStore:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /acta-ui/api/ProjectPlaceDataExtractor
      Type: String
      Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/extract-project-place'

Outputs:
  ApiUrl:
    Description: API endpoint URL
    Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'

  TimelineParam:
    Description: Timeline URL
    Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/timeline'
    Export:
      Name: ActaUiApiGetTimeline
      
  DownloadParam:
    Description: Download URL
    Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/download-acta'
    Export:
      Name: ActaUiApiGetDownloadActa

  SummaryParam:
    Description: Summary URL
    Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/project-summary'
    Export:
      Name: ActaUiApiGetProjectSummary

  SendEmailParam:
    Description: Send approval email URL
    Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/send-approval-email'
    Export:
      Name: ActaUiApiSendApprovalEmail

  ExtractParam:
    Description: Extract ProjectPlace URL
    Value: !Sub 'https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/extract-project-place'
    Export:
      Name: ActaUiApiProjectPlaceDataExtractor
