name: Deploy UI

on:
  push:
    branches: [develop]
  workflow_dispatch:

permissions: # ⚠️  REQUIRED for OIDC
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & build
        env:
          CI: true
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Install AWS CLI if missing
        run: |
          if ! command -v aws >/dev/null; then
            pip install --user awscli
            echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          fi

      # ---------- OIDC credentials ----------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ---------- Deploy ----------
      - name: Deploy to S3 + invalidate CloudFront
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          CLOUDFRONT_DIST_ID: ${{ secrets.CLOUDFRONT_DIST_ID }}
        run: |
          chmod +x scripts/deploy-to-s3.sh
          ./scripts/deploy-to-s3.sh
