name: 🚀 ACTA-UI Production Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force full rebuild and deployment'
        required: false
        default: false
        type: boolean

# Prevent concurrent deployments
concurrency:
  group: production-deploy
  cancel-in-progress: true

env:
  NODE_VERSION: '18'
  # Production environment variables
  VITE_API_BASE_URL: 'https://q2b9avfwv5.execute-api.us-east-2.amazonaws.com/prod'
  VITE_COGNITO_REGION: 'us-east-2'
  VITE_COGNITO_POOL_ID: 'us-east-2_FyHLtOhiY'
  VITE_COGNITO_WEB_CLIENT: 'dshos5iou44tuach7ta3ici5m'
  VITE_SKIP_AUTH: 'false'
  VITE_USE_MOCK_API: 'false'
  # AWS Resources
  CLOUDFRONT_DISTRIBUTION: 'd7t9x3j66yd8k'
  S3_BUCKET: 'acta-ui-production'
  AWS_REGION: 'us-east-2'

jobs:
  build-and-deploy:
    name: 🏗️ Build & Deploy Production
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
      
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
        
      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.9
          
      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          
      - name: 📦 Install Dependencies
        run: |
          echo "🧹 Clearing caches..."
          rm -rf node_modules/.vite dist .cache
          pnpm install --frozen-lockfile
          
      - name: 🔍 Environment Verification
        run: |
          echo "🔍 Verifying production environment..."
          echo "API Base URL: $VITE_API_BASE_URL"
          echo "Cognito Pool: $VITE_COGNITO_POOL_ID"
          echo "Skip Auth: $VITE_SKIP_AUTH"
          echo "Use Mock API: $VITE_USE_MOCK_API"
          
      - name: 🏗️ Build Application
        run: |
          echo "🚀 Building for production..."
          pnpm run build
          echo "✅ Build completed!"
          
      - name: 🧪 Build Verification
        run: |
          echo "🔍 Verifying build output..."
          
          # Check document title
          if grep -q "Ikusi · Acta Platform" dist/index.html; then
            echo "✅ Document title correct"
          else
            echo "❌ Document title incorrect"
            exit 1
          fi
          
          # Check production API URL
          if grep -q "q2b9avfwv5.execute-api.us-east-2.amazonaws.com" dist/assets/*.js; then
            echo "✅ Production API URL found"
          else
            echo "❌ Production API URL not found"
            exit 1
          fi
          
          # Verify no test/mock data
          if grep -r "test-project\|mock-project" dist/ 2>/dev/null; then
            echo "❌ Test data found in build"
            exit 1
          else
            echo "✅ No test data in build"
          fi
          
          echo "🎯 Build verification passed!"
          
      - name: 🔧 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: 📤 Deploy to S3
        run: |
          echo "📤 Deploying to S3 bucket..."
          
          # Deploy build files to S3
          aws s3 sync dist/ s3://$S3_BUCKET/ \
            --delete \
            --cache-control "max-age=31536000" \
            --exclude "*.html" \
            --exclude "*.json"
          
          # Deploy HTML/JSON with no-cache
          aws s3 sync dist/ s3://$S3_BUCKET/ \
            --cache-control "max-age=0,no-cache,no-store,must-revalidate" \
            --include "*.html" \
            --include "*.json"
          
          echo "✅ S3 deployment completed!"
          
      - name: 🔄 Invalidate CloudFront
        run: |
          echo "🔄 Invalidating CloudFront cache..."
          
          INVALIDATION_ID=$(aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION \
            --paths "/*" \
            --query 'Invalidation.Id' \
            --output text)
          
          echo "✅ CloudFront invalidation created: $INVALIDATION_ID"
          
          # Wait for invalidation to complete
          echo "⏳ Waiting for cache invalidation..."
          aws cloudfront wait invalidation-completed \
            --distribution-id $CLOUDFRONT_DISTRIBUTION \
            --id $INVALIDATION_ID
          
          echo "✅ CloudFront cache invalidated!"
          
      - name: 🧪 Deployment Verification
        run: |
          echo "🧪 Verifying deployment..."
          
          # Wait for deployment to propagate
          sleep 30
          
          # Test main application
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://d7t9x3j66yd8k.cloudfront.net/)
          if [ "$RESPONSE" = "200" ]; then
            echo "✅ Application accessible: HTTP $RESPONSE"
          else
            echo "❌ Application not accessible: HTTP $RESPONSE"
            exit 1
          fi
          
          # Test API connectivity with CORS
          CORS_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Origin: https://d7t9x3j66yd8k.cloudfront.net" \
            -H "Access-Control-Request-Method: GET" \
            -X OPTIONS \
            https://q2b9avfwv5.execute-api.us-east-2.amazonaws.com/prod/health)
          
          if [ "$CORS_RESPONSE" = "200" ]; then
            echo "✅ CORS configuration working: HTTP $CORS_RESPONSE"
          else
            echo "❌ CORS configuration issue: HTTP $CORS_RESPONSE"
            exit 1
          fi
          
          echo "🎯 Deployment verification passed!"
          
      - name: 🎉 Deployment Success
        run: |
          echo "🎉 ACTA-UI Production Deployment Successful!"
          echo ""
          echo "🌐 Live Application: https://d7t9x3j66yd8k.cloudfront.net"
          echo "🔌 API Gateway: https://q2b9avfwv5.execute-api.us-east-2.amazonaws.com/prod"
          echo "🔐 Authentication: AWS Cognito enabled"
          echo "🌍 CORS: Properly configured"
          echo ""
          echo "✅ Production deployment completed successfully!"

  smoke-tests:
    name: 🧪 Production Smoke Tests
    needs: build-and-deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
        
      - name: 🧪 Run Smoke Tests
        run: |
          echo "🧪 Running production smoke tests..."
          
          # Test application loads
          RESPONSE=$(curl -s -w "%{http_code}\n" https://d7t9x3j66yd8k.cloudfront.net/ | tail -n1)
          if [ "$RESPONSE" = "200" ]; then
            echo "✅ Application loads successfully"
          else
            echo "❌ Application failed to load: HTTP $RESPONSE"
            exit 1
          fi
          
          # Test API health endpoint
          API_RESPONSE=$(curl -s -w "%{http_code}\n" https://q2b9avfwv5.execute-api.us-east-2.amazonaws.com/prod/health | tail -n1)
          if [ "$API_RESPONSE" = "200" ] || [ "$API_RESPONSE" = "403" ]; then
            echo "✅ API Gateway responding: HTTP $API_RESPONSE"
          else
            echo "❌ API Gateway not responding: HTTP $API_RESPONSE"
            exit 1
          fi
          
          echo "🎯 All smoke tests passed!"
