name: Deploy UI → S3 + CloudFront

on:
  push:
    branches: [develop]     # ⬅️ auto-deploy only from ♦ develop ♦
  workflow_dispatch: {}     # manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read

    steps:
      # 0 Checkout
      - uses: actions/checkout@v4

      # 0.1 Static /health stub
      - name: 💚 add /health
        run: mkdir -p public && echo '{"status":"ok"}' > public/health

      # 1 Node + pnpm
      - uses: pnpm/action-setup@v2
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile

      # 2 Build
      - name: Inject API base URL
        run: echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> "$GITHUB_ENV"
      - name: 🏗️ Build (Vite)
        run: pnpm run build
      - name: Copy SPA client routes
        run: bash scripts/push-spa-routes.sh        # ↖︎ keeps /login & /dashboard working

      # 3 Local smoke-test
      - name: 🌐 preview smoke
        run: |
          pnpm exec vite preview --port 4173 --strictPort & SERVER=$!
          sleep 4 && curl -sf http://localhost:4173/ && kill $SERVER

      # 4 AWS cred-helper (OIDC)
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 5 Upload + invalidate
      - name: 🚀 Sync to S3 + purge CF
        env:
          DEPLOY_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          CF_DIST_ID:    ${{ secrets.CLOUDFRONT_DIST_ID }}
        run: |
          set -eux
          aws s3 sync dist/ "s3://$DEPLOY_BUCKET" --delete
          bash scripts/push-spa-routes.sh
          INV=$(aws cloudfront create-invalidation \
              --distribution-id "$CF_DIST_ID" --paths '/*' \
              --query 'Invalidation.Id' --output text)
          aws cloudfront wait invalidation-completed \
              --distribution-id "$CF_DIST_ID" --id "$INV"
