name: Smoke – Prod

on:
  workflow_run:
    workflows: ['Build and Deploy'] # must match name above
    types: [completed]

jobs:
  probe_cf_health:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Ping /health via CloudFront
        env:
          DIST_ID: ${{ secrets.CLOUDFRONT_DIST_ID }}
        run: |
          CF_DOMAIN=$(aws cloudfront get-distribution \
            --id "$DIST_ID" --query 'Distribution.DomainName' --output text)
          echo "Domain: $CF_DOMAIN"
          curl -fs "https://$CF_DOMAIN/health"
