# .github/workflows/smoke-prod.yml
name: Smoke – Prod

on:
  workflow_run:
    workflows: [UI Deploy]
    types: [completed]
    branches: [develop]

jobs:
  smoke_prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # ⇣  NEW ­– OIDC creds (same role you use for deploy, read access is fine)
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 🌡️ /health via CloudFront
        env:
          DIST_ID: ${{ secrets.CLOUDFRONT_DIST_ID }}
        run: |
          set -e
          CF_DOMAIN=$(aws cloudfront get-distribution \
            --id "$DIST_ID" --query 'Distribution.DomainName' --output text)
          echo "Domain: $CF_DOMAIN"
          curl -fs "https://$CF_DOMAIN/health"
